### ISSUE TITLE
Fehlermeldung vom 2022_05_02

### ISSUE THREAD

**Issue by chrissikay** [T-i-M-M-i/DE4LRoadTracker#30]
@bastiion kannst du damit etwas anfangen?

```
Hi Georg,
ich habe soeben eure DE4L Roadtracker-App getestet (Version 0.2.3). Die App funktioniert nicht richtig, es werden keine Daten übertragen.

Im LogCat taucht folgender Fehler auf:
2022-05-02 13:33:26.836 28516-28516/? W/System.err: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lfilter.Distance.distanceMany(Unknown Source:22)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lroadtracker.helper.AggregateAndFilter.processResults(AggregateAndFilter.java:94)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lroadtracker.helper.Publisher.filterAndPublish(Publisher.java:37)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lroadtracker.MainActivity.filterAndPublish(MainActivity.java:194)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lroadtracker.MainActivity.stopTrackingService(MainActivity.java:296)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at io.timmi.de4lroadtracker.MainActivity.toggleService(MainActivity.java:324)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.onMenuItemClick(SupportMenuInflater.java:267)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.view.View.performClick(View.java:7455)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.view.View.performClickInternal(View.java:7432)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.view.View.access$3700(View.java:835)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.view.View$PerformClick.run(View.java:28810)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7870)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2022-05-02 13:33:26.836 28516-28516/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
 
Viele Grüße,
Benni
```

**Comment by bastiion** [comment]
@johannesloetzsch to be honest, I cannot really track down this error. Because it happens in the Clojure code and the Call is wrapped by a general try-catch block, which should catch these kind of errors. The only thing that I did addionally is to get a long value and compare it, with `Double.MAX_VALUE` whether it is within that range. But it seems to me more like he might be  using an older version of the App.
